- hosts: installer
  pre_tasks:
    - name: Importing variables
      set_fact:
        masters_parsed: "{{ masters | list }}"
        workers_parsed: "{{ workers | list }}"
        installer_parsed: "{{ installer | list }}"
  remote_user: root
  roles:
  - installer
- hosts: ocp_workers,ocp_masters
  remote_user: root
  roles:
  - cluster
- hosts: installer
  remote_user: root
  roles:
  - openshift_installer
- hosts: ocp_masters
  remote_user: root
  tasks:
  - name: setting cluster-admin role
    command: oc create clusterrolebinding ocpadmin --clusterrole cluster-admin --user ocpadmin
  ignore_errors: yes
- hosts: installer
  remote_user: root
  roles:
  - cp4d_installer