- name: reload NetworkManager
  service:
    name: NetworkManager
    state: reloaded
- name: reboot machine
  reboot:
- name: restart docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
