- name: gather keyfiles for {{ item.name }} (1/3)
  command: ssh-keyscan {{ item.name }}.{{ cluster_domain }}
  register: item_cluster_domain_key
- name: gather keyfiles for {{ item.name }} (2/3)
  command: ssh-keyscan {{ item.name }}
  register: item_key
- name: gather keyfiles for {{ item.name }} (3/3)
  command: ssh-keyscan {{ item.private_ip }}
  register: item_private_ip_key
- name: add keyfiles for {{ item.name }} to known hosts (1/3)
  lineinfile:
    path: /root/.ssh/known_hosts
    create: yes
    line: "{{ item_cluster_domain_key.stdout_lines[0] }}"
- name: add keyfiles for {{ item.name }} to known hosts (2/3)
  lineinfile:
    path: /root/.ssh/known_hosts
    line: "{{ item_key.stdout_lines[0] }}"
- name: add keyfiles for {{ item.name }} to known_hosts (3/3)
  lineinfile:
    path: /root/.ssh/known_hosts
    line: "{{ item_private_ip_key.stdout_lines[0] }}"